name: lint
on:
  push:
  pull_request:

# Cancel in-progress runs for PRs when there are new pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
      - uses: golangci/golangci-lint-action@v4
        with:
          args: --timeout=5m
          skip-cache: false
