# .github/workflows/release.yml
name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

# Don't cancel release builds as they're triggered by tags
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
      - run: git fetch --tags
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.STOIC_SECRET }}
          # TODO: enable goreleaser pro when ready
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
